apiVersion: batch/v1
kind: Job
metadata:
  name: n2-dataloader
  namespace: default
  labels:
    app: dataloader
spec:
  template:
    metadata:
      labels:
        app: job
    spec:
      volumes:
        - name: c2n2-connection-bundle
          secret:
            secretName: c2n2-connection-bundle
      containers:
      - name: dataloader
        image: scylladb/hydra-loaders:scylla-bench-v0.1.16
        volumeMounts:
        - name: c2n2-connection-bundle
          mountPath: /var/run/secrets/kubernetes.io/connbundle
          readOnly: true
        command:
          - "/bin/bash"
          - "-c"
          - 'time scylla-bench -workload=sequential -mode=write -concurrency=20 -partition-count=500 -clustering-row-count=10000000 -clustering-row-size=100 -consistency-level=all -rows-per-request=50000 -validate-data -cloud-config-path /var/run/secrets/kubernetes.io/connbundle/sc2.ml.virgil.scylla-operator.scylladb.com'
        resources:
          limits:
            cpu: 4
            memory: 4G
      restartPolicy: Never