apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: metering-lab-c1
  region: us-east-1

availabilityZones:
- us-east-1a
- us-east-1b
- us-east-1d

nodeGroups:
- name: scylla-pool
  instanceType: i3.xlarge
  desiredCapacity: 3
  labels:
    pool: "scylla-pool"
  taints:
    role: "scylla-clusters:NoSchedule"
  ssh:
    allow: true
  kubeletExtraConfig:
    cpuManagerPolicy: static
  availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1d

- name: monitoring-pool
  instanceType: i3.large
  desiredCapacity: 1
  labels:
    pool: "monitoring-pool"
  ssh:
    allow: true
