apiVersion: v1
kind: Service
metadata:
  name: ingress-default-backend
spec:
  selector:
    app.kubernetes.io/name: ingress-default-backend
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: cql-ssl
    port: 9142
    protocol: TCP
    targetPort: 443
