apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-default-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-default-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-default-backend
    spec:
      containers:
      - name: ingress-default-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
