apiVersion: batch/v1
kind: Job
metadata:
  name: dataloader
  namespace: default
  labels:
    app: dataloader
spec:
  parallelism: 4
  template:
    metadata:
      labels:
        app: job
    spec:
      volumes:
        - name: connection-bundle
          secret:
            secretName: c1-connection-bundle
      containers:
      - name: dataloader
        image: scylladb/scylla-bench:latest
        volumeMounts:
        - name: connection-bundle
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
        command:
          - "/bin/bash"
          - "-c"
          - 'scylla-bench -tls true -workload sequential -mode write -nodes n1,n2,n3 -clustering-row-size 16 -validate-data -tls-ca-cert-file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        resources:
          limits:
            cpu: 7
            memory: 12G
      restartPolicy: Never
      tolerations:
        - key: role
          operator: Equal
          value: dataloader
          effect: NoSchedule
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - job
            topologyKey: "kubernetes.io/hostname"
