apiVersion: batch/v1
kind: Job
metadata:
  name: dataloader
  namespace: default
  labels:
    app: dataloader
spec:
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
      - name: dataloader
        image: scylladb/scylla-bench:latest
        command:
          - "/bin/bash"
          - "-c"
          - 'scylla-bench -workload sequential -mode write -nodes n1,n2,n3 -clustering-row-size 16 -validate-data'
        resources:
          limits:
            cpu: 30
            memory: 60G
      restartPolicy: Never
      tolerations:
        - key: role
          operator: Equal
          value: dataloader
          effect: NoSchedule
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - job
            topologyKey: "kubernetes.io/hostname"
