apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: metering-lab-c2
  region: us-east-1
  version: "1.23"

availabilityZones:
- us-east-1a
- us-east-1b

nodeGroups:
- name: cassandra-stress-pool
  instanceType: c4.2xlarge
  desiredCapacity: 1
  labels:
    pool: "cassandra-stress-pool"
  ssh:
    allow: true
  tags:
    keep: alive