apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: metering-lab-c2
  region: us-east-1

availabilityZones:
- us-east-1a

nodeGroups:
- name: cassandra-stress-pool
  instanceType: c4.2xlarge
  desiredCapacity: 4
  labels:
    pool: "cassandra-stress-pool"
  taints:
    role: "cassandra-stress:NoSchedule"
  ssh:
    allow: true
  preBootstrapCommands:
  - curl -o /etc/yum.repos.d/scylla.repo -L http://repositories.scylladb.com/scylla/repo/3e3ec6ec-92b2-46ec-b64f-5b2338bc47de/centos/scylladb-4.0.repo
  - yum install -y scylla-tools